deadlines:
  '3':
    Wed:
      date: 2023/09/20 11:00am 
      content: ip1
  '4':
    Wed:
      date: 2023/09/27 11:00am 
      content: tp1
  '6':
    Wed:
      date: 2023/10/11 11:00am
      content: tp2
  '7':
    Wed:
      date: 2023/10/18 11:00am
      content: ip2
  '8':
    Wed:
      date: 2023/10/25 11:00am
      content: tp3
  '13':
    Wed:
      date: 2023/11/29 11:00am
      content: tp4
dates:
  firstMonday: 2023/09/04
  numWeeks: 14
types:
  default:
    className: lesson
  holiday:
    className: holiday