deadlines:
  '3':
    Wed:
      date: 2023/01/25 11:00am 
      content: ip1
  '4':
    Wed:
      date: 2023/02/01 11:00am 
      content: tp1
  '6':
    Wed:
      date: 2023/02/15 11:00am
      content: tp2
  '7':
    Wed:
      date: 2023/02/22 11:00am
      content: ip2
  '8':
    Wed:
      date: 2023/03/01 11:00am
      content: tp3
  '14':
    Wed:
      date: 2023/04/12 11:00am
      content: tp4
dates:
  firstMonday: 2023/01/09
  numWeeks: 15
types:
  default:
    className: lesson
  holiday:
    className: holiday